#### WAF Create item if it doesn't exist ###
- name: "{{ request_comment }}"
  uri:
    url: "{{ request_url }}{{ request_path }}/{{ request_name }}"
    method: GET
    user: "{{ waf_token.json.token }}"
    password: ""
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    status_code: 200
  ignore_errors: True
  register: result
  until: result.status != -1
#- debug:
#    msg: "{{service.json}}"

- name: Create "{{ request_name }}"
  when: result is failed
  uri:
    url: "{{ request_url }}{{ request_path }}"
    method: POST
    user: "{{ waf_token.json.token }}"
    password: ""
    force_basic_auth: yes
    body: "{{ request_body }}"
    body_format: json
    timeout: 60
    headers:
      Content-Type: "application/json"
    status_code: 201
  register: result2
  until: result2.status != -1
