#### WAF Create or edit item ###
- name: "{{ request_comment }}"
  uri:
    url: "{{ request_url }}{{ request_path }}/{{ request_name }}"
    method: GET
    user: "{{ waf_token.json.token }}"
    password: ""
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    status_code: 200, 404
  register: result
  ignore_errors: True
  until: result.status != -1

- name: Create "{{ request_name }}"
  when: result.status == 404
  uri:
    url: "{{ request_url }}{{ request_path }}"
    method: POST
    user: "{{ waf_token.json.token }}"
    password: ""
    force_basic_auth: yes
    body: "{{ request_body }}"
    body_format: json
    timeout: 60
    headers:
      Content-Type: "application/json"
    status_code: 201
  register: result2
  until: result2.status != -1

- name: Edit "{{ request_name }}"
  when: result.status == 200
  uri:
    url: "{{ request_url }}{{ request_path }}/{{ request_name }}"
    method: PUT
    user: "{{ waf_token.json.token }}"
    password: ""
    force_basic_auth: yes
    body: "{{ request_body }}"
    body_format: json
    headers:
      Content-Type: "application/json"
    status_code: 200
  register: result2
  until: result2.status != -1
